export interface SegmentPassport {
  id: string;
  slug: string;
  name: string;
  fullName: string;
  status: 'active' | 'draft' | 'test' | 'archived';
  priority: 'high' | 'medium' | 'low';
  order: number;
  featuredOnHome: boolean;
  seo: {
    title: string;
    description: string;
    h1: string;
    canonical?: string;
    ogImage: string;
    noIndex?: boolean;
  };
  hero: {
    title: string;
    subtitle: string;
    ctaPrimary: string;
    ctaSecondary: string;
    benefits: string[];
    microProof: string;
    image: string;
  };
  forWhom: string[];
  painPoints: {
    business: string[];
    procurement: string[];
    exploitation: string[];
  };
  solutions: {
    title: string;
    description: string;
    type: 'product' | 'process' | 'benefit';
  }[];
  bundles: {
    title: string;
    description: string;
    items: string[];
  }[];
  evidence: {
    cases: {
      type: 'real' | 'example' | 'review' | 'photo';
      title: string;
      description: string;
      image: string;
      metrics?: string;
    }[];
  };
  howItWorks: { title: string; description: string }[];
  form: {
    title: string;
    subtitle: string;
    submitLabel: string;
    fields: { name: string; label: string; type: 'text' | 'number' | 'select' | 'tel' | 'textarea'; required: boolean; placeholder?: string }[];
    hiddenFields: Record<string, string>;
    successMessage: string;
    formType: 'short' | 'extended';
    successAction: 'message' | 'redirect';
  };
  faq: { q: string; a: string }[];
  finalCta: {
    title: string;
    description: string;
    buttonText: string;
  };
  tracking: {
    segment: string;
    segmentLabel: string;
    offer: string;
    pageType: string;
    scenarioId: string;
    pipeline: string;
    tags: string[];
    formId: string;
    ownerQueue: string;
    sourceDefault: string;
  };
  assets: {
    heroImage: string;
    ogImage: string;
    hubCard: {
      icon: string;
      title: string;
      description: string;
      cta: string;
    };
  };
}

export const segments: Record<string, SegmentPassport> = {
  autoservice: {
    id: 'autoservice',
    slug: 'autoservice',
    name: 'Автосервисы',
    fullName: 'Форма для автосервисов',
    status: 'active',
    priority: 'high',
    order: 1,
    featuredOnHome: true,
    seo: {
      title: 'Брендированная форма для автосервисов',
      description: 'Износостойкая одежда для механиков с логотипом.',
      h1: 'Брендированная форма для автосервисов',
      ogImage: 'https://picsum.photos/seed/autoservice/1200/630',
    },
    hero: {
      title: 'Нанесем логотип на форму для автосервиса, который не выцветает и держится в работе',
      subtitle: 'Быстро печатаем на вашей одежде — поможем с формой при необходимости',
      ctaPrimary: 'Получить расчет',
      ctaSecondary: 'Смотреть примеры',
      benefits: ['Не выцветает', 'Держится в работе', 'Быстрая печать'],
      microProof: 'Поможем с формой при необходимости',
      image: 'https://picsum.photos/seed/autoservice/1920/1080',
    },
    forWhom: ['Автосервисы', 'СТО', 'Шиномонтаж', 'Автомойки', 'Детейлинг'],
    painPoints: {
      business: ['Сотрудники выглядят по-разному', 'Нет единого фирменного вида'],
      procurement: ['Сложно быстро нанести логотип на форму', 'Нужно решение без долгого производства'],
      exploitation: ['Логотип стирается после стирок', 'Форма быстро теряет внешний вид'],
    },
    solutions: [
      { title: 'Подбираем одежду под условия работы', description: 'Учитываем нагрузку, тип работ и комфорт сотрудников', type: 'product' },
      { title: 'Наносим логотип, который держится', description: 'Печать или вышивка — подбираем под задачу', type: 'process' },
      { title: 'Делаем комплекты под ваш штат', description: 'Сразу подбираем размеры и количество', type: 'product' },
      { title: 'Помогаем масштабироваться', description: 'Можно быстро дозаказывать такую же форму без хаоса', type: 'benefit' },
    ],
    bundles: [
      { title: 'Базовый комплект', description: 'Подходит для ежедневной работы', items: ['Футболка с логотипом', 'Рабочая кофта'] },
      { title: 'Комплект механика', description: 'Для активной работы в цеху', items: ['Футболка', 'Толстовка / куртка', 'Рабочие штаны'] },
      { title: 'Комплект мастера / администратора', description: 'Для тех, кто работает с клиентами', items: ['Поло / футболка', 'Легкая кофта'] },
    ],
    evidence: {
      cases: [
        { type: 'real', title: 'Комплект для СТО на 12 человек', description: 'Полный комплект формы, сделали за 7 дней', image: 'https://picsum.photos/seed/case1/400/300' },
        { type: 'real', title: 'Форма для автомойки', description: 'Влагостойкие фартуки, сделали за 5 дней', image: 'https://picsum.photos/seed/case2/400/300' },
        { type: 'real', title: 'Футболки с логотипом для шиномонтажа', description: 'Износостойкий принт, сделали за 3 дня', image: 'https://picsum.photos/seed/case3/400/300' },
      ],
    },
    howItWorks: [
      { title: 'Оставляете заявку', description: 'Заполните форму, и мы свяжемся с вами' },
      { title: 'Уточняем задачу', description: 'Обсуждаем количество сотрудников и условия работы' },
      { title: 'Предлагаем варианты', description: 'Подбираем одежду и метод нанесения' },
      { title: 'Согласовываем', description: 'Утверждаем макет и размеры' },
      { title: 'Производим и доставляем', description: 'Отшиваем партию и привозим вам' },
    ],
    form: {
      title: 'Подберем форму под ваш автосервис',
      subtitle: 'Предложим варианты под ваш штат и задачи',
      submitLabel: 'Получить расчет',
      fields: [
        { name: 'name', label: 'Имя', type: 'text', required: true },
        { name: 'phone', label: 'Телефон', type: 'tel', required: true },
        { name: 'mechanicsCount', label: 'Количество механиков', type: 'number', required: true },
        { name: 'comment', label: 'Комментарий', type: 'textarea', required: false },
      ],
      hiddenFields: { segment: 'autoservice', offer: 'uniform_mechanics' },
      successMessage: 'Спасибо! Мы свяжемся с вами в ближайшее время.',
      formType: 'short',
      successAction: 'message',
    },
    faq: [
      { q: 'Какой минимальный заказ?', a: 'Зависит от типа изделия — подскажем после заявки' },
      { q: 'Можно ли дозаказывать потом?', a: 'Да, сохраняем все параметры и делаем повтор' },
      { q: 'Логотип не сотрется?', a: 'Подбираем способ нанесения под условия работы' },
      { q: 'Вы помогаете с выбором?', a: 'Да, подбираем под ваш формат работы' },
    ],
    finalCta: {
      title: 'Подберем форму под ваш автосервис',
      description: 'Соберем комплект под ваш штат и предложим варианты под ваш бюджет',
      buttonText: 'Получить расчет',
    },
    tracking: {
      segment: 'autoservice',
      segmentLabel: 'Автосервисы',
      offer: 'uniform_mechanics',
      pageType: 'segment',
      scenarioId: 'autoservice_scenario',
      pipeline: 'standard',
      tags: ['autoservice'],
      formId: 'autoservice_form',
      ownerQueue: 'sales',
      sourceDefault: 'website',
    },
    assets: {
      heroImage: 'https://picsum.photos/seed/autoservice/1920/1080',
      ogImage: 'https://picsum.photos/seed/autoservice/1200/630',
      hubCard: {
        icon: '🔧',
        title: 'Автосервисы',
        description: 'Износостойкая форма для механиков с логотипом под ваш штат.',
        cta: 'Посмотреть решение',
      },
    },
  },
  cafe: {
    id: 'cafe',
    slug: 'cafe',
    name: 'Кафе и рестораны',
    fullName: 'Форма для кафе и ресторанов',
    status: 'active',
    priority: 'high',
    order: 2,
    featuredOnHome: true,
    seo: {
      title: 'Стильная форма для персонала кафе',
      description: 'Фартуки, футболки и худи для персонала с брендингом.',
      h1: 'Стильная форма для персонала кафе',
      ogImage: 'https://picsum.photos/seed/cafe/1200/630',
    },
    hero: {
      title: 'Нанесем логотип на форму для кафе — аккуратно, стильно и без потери внешнего вида',
      subtitle: 'Работаем с вашей одеждой или подскажем варианты',
      ctaPrimary: 'Получить расчет',
      ctaSecondary: 'Смотреть примеры',
      benefits: ['Аккуратно', 'Стильно', 'Без потери вида'],
      microProof: 'Работаем с вашей одеждой или подскажем варианты',
      image: 'https://picsum.photos/seed/cafe/1920/1080',
    },
    forWhom: ['Кофейни', 'Рестораны', 'Бары', 'Пекарни', 'Фастфуд'],
    painPoints: {
      business: ['Персонал выглядит разрозненно', 'Форма не поддерживает стиль'],
      procurement: ['Сложно быстро брендировать форму', 'Нет удобного решения'],
      exploitation: ['Логотип вымывается', 'Форма теряет аккуратность'],
    },
    solutions: [
      { title: 'Подбираем форму под стиль заведения', description: 'Учитываем интерьер и атмосферу', type: 'product' },
      { title: 'Разделяем решения для зала и кухни', description: 'Комфорт и функциональность', type: 'product' },
      { title: 'Наносим логотип аккуратно', description: 'Брендинг, который держится', type: 'process' },
      { title: 'Собираем комплекты под команду', description: 'Размеры и количество', type: 'benefit' },
    ],
    bundles: [{ title: 'Комплект бариста', description: 'Фартук + футболка', items: ['Фартук', 'Футболка'] }],
    evidence: { cases: [{ type: 'real', title: 'Кофейня "Зерно"', description: 'Полный комплект формы', image: 'https://picsum.photos/seed/case2/400/300' }] },
    howItWorks: [
      { title: 'Оставляете заявку', description: 'Заполните форму, и мы свяжемся с вами' },
      { title: 'Уточняем задачу', description: 'Обсуждаем стиль и количество сотрудников' },
      { title: 'Предлагаем варианты', description: 'Подбираем одежду и метод нанесения' },
      { title: 'Согласовываем', description: 'Утверждаем макет и размеры' },
      { title: 'Производим и доставляем', description: 'Отшиваем партию и привозим вам' },
    ],
    form: {
      title: 'Подберем форму под ваше кафе и формат работы',
      subtitle: 'Предложим варианты под ваш стиль, формат и количество сотрудников',
      submitLabel: 'Получить расчет',
      fields: [
        { name: 'name', label: 'Имя', type: 'text', required: true },
        { name: 'phone', label: 'Телефон', type: 'tel', required: true },
        { name: 'staffCount', label: 'Количество персонала', type: 'number', required: true },
      ],
      hiddenFields: { segment: 'cafe', offer: 'uniform_cafe' },
      successMessage: 'Спасибо! Мы свяжемся с вами в ближайшее время.',
      formType: 'short',
      successAction: 'message',
    },
    faq: [{ q: 'Можно ли заказать разные размеры?', a: 'Да, конечно.' }],
    finalCta: { title: 'Готовы начать?', description: 'Подберем комплект под ваш штат', buttonText: 'Получить расчет' },
    tracking: {
      segment: 'cafe',
      segmentLabel: 'Кафе и рестораны',
      offer: 'uniform_cafe',
      pageType: 'segment',
      scenarioId: 'cafe_scenario',
      pipeline: 'standard',
      tags: ['cafe'],
      formId: 'cafe_form',
      ownerQueue: 'sales',
      sourceDefault: 'website',
    },
    assets: {
      heroImage: 'https://picsum.photos/seed/cafe/1920/1080',
      ogImage: 'https://picsum.photos/seed/cafe/1200/630',
      hubCard: {
        icon: '☕',
        title: 'Кафе и рестораны',
        description: 'Форма, которая усиливает стиль заведения и выглядит аккуратно.',
        cta: 'Посмотреть решение',
      },
    },
  },
  factory: {
    id: 'factory',
    slug: 'factory',
    name: 'Производства',
    fullName: 'Форма для производств',
    status: 'active',
    priority: 'high',
    order: 3,
    featuredOnHome: true,
    seo: {
      title: 'Рабочая одежда для производств',
      description: 'Массовые тиражи спецодежды с логотипом.',
      h1: 'Рабочая одежда для производств',
      ogImage: 'https://picsum.photos/seed/factory/1200/630',
    },
    hero: {
      title: 'Нанесем логотип на спецодежду для производства — под объемы и регулярные заказы',
      subtitle: 'Работаем быстро и стабильно',
      ctaPrimary: 'Получить расчет',
      ctaSecondary: 'Смотреть примеры',
      benefits: ['Объемы', 'Стабильность', 'Быстро'],
      microProof: 'Работаем быстро и стабильно',
      image: 'https://picsum.photos/seed/factory/1920/1080',
    },
    forWhom: ['Заводы', 'Цеха', 'Склады', 'Производственные компании'],
    painPoints: {
      business: ['Нет единого внешнего вида', 'Слабый корпоративный стиль'],
      procurement: ['Нужны объемы и стабильность', 'Сложно найти подрядчика'],
      exploitation: ['Логотип стирается', 'Форма изнашивается'],
    },
    solutions: [
      { title: 'Работаем с большими тиражами', description: 'Обеспечиваем объемы', type: 'product' },
      { title: 'Подбираем под условия производства', description: 'Износостойкость', type: 'product' },
      { title: 'Обеспечиваем повторяемость', description: 'Стабильное качество', type: 'benefit' },
      { title: 'Настраиваем систему дозаказа', description: 'Удобство закупок', type: 'process' },
    ],
    bundles: [{ title: 'Комплект рабочего', description: 'Куртка + брюки', items: ['Куртка', 'Брюки'] }],
    evidence: { cases: [{ type: 'real', title: 'Завод "Металл"', description: 'Полный комплект формы', image: 'https://picsum.photos/seed/case3/400/300' }] },
    howItWorks: [
      { title: 'Оставляете заявку', description: 'Заполните форму, и мы свяжемся с вами' },
      { title: 'Уточняем задачу', description: 'Обсуждаем тираж и условия' },
      { title: 'Предлагаем варианты', description: 'Подбираем одежду и метод нанесения' },
      { title: 'Согласовываем', description: 'Утверждаем макет и размеры' },
      { title: 'Производим и доставляем', description: 'Отшиваем партию и привозим вам' },
    ],
    form: {
      title: 'Рассчитаем спецодежду под ваше производство',
      subtitle: 'Подберем варианты под объем и задачи',
      submitLabel: 'Получить расчет',
      fields: [
        { name: 'name', label: 'Имя', type: 'text', required: true },
        { name: 'phone', label: 'Телефон', type: 'tel', required: true },
        { name: 'volume', label: 'Примерный тираж', type: 'number', required: true },
      ],
      hiddenFields: { segment: 'factory', offer: 'uniform_factory' },
      successMessage: 'Спасибо! Мы свяжемся с вами в ближайшее время.',
      formType: 'short',
      successAction: 'message',
    },
    faq: [{ q: 'Какие сроки?', a: 'Зависит от тиража.' }],
    finalCta: { title: 'Готовы начать?', description: 'Подберем комплект под ваш штат', buttonText: 'Рассчитать' },
    tracking: {
      segment: 'factory',
      segmentLabel: 'Производства',
      offer: 'uniform_factory',
      pageType: 'segment',
      scenarioId: 'factory_scenario',
      pipeline: 'standard',
      tags: ['factory'],
      formId: 'factory_form',
      ownerQueue: 'sales',
      sourceDefault: 'website',
    },
    assets: {
      heroImage: 'https://picsum.photos/seed/factory/1920/1080',
      ogImage: 'https://picsum.photos/seed/factory/1200/630',
      hubCard: {
        icon: '🏭',
        title: 'Производства',
        description: 'Спецодежда под большие тиражи и стабильные дозаказы.',
        cta: 'Посмотреть решение',
      },
    },
  },
  beauty: {
    id: 'beauty',
    slug: 'beauty',
    name: 'Салоны красоты',
    fullName: 'Форма для салонов красоты',
    status: 'active',
    priority: 'high',
    order: 4,
    featuredOnHome: true,
    seo: {
      title: 'Стильная форма для салонов красоты',
      description: 'Аккуратная одежда для мастеров с брендингом.',
      h1: 'Стильная форма для салонов красоты',
      ogImage: 'https://picsum.photos/seed/beauty/1200/630',
    },
    hero: {
      title: 'Нанесем логотип на форму для салона — аккуратно и в вашем стиле',
      subtitle: 'Чтобы внешний вид усиливал бренд',
      ctaPrimary: 'Получить расчет',
      ctaSecondary: 'Смотреть примеры',
      benefits: ['Аккуратно', 'Ваш стиль', 'Усиливает бренд'],
      microProof: 'Чтобы внешний вид усиливал бренд',
      image: 'https://picsum.photos/seed/beauty/1920/1080',
    },
    forWhom: ['Салоны красоты', 'Барбершопы', 'SPA-центры'],
    painPoints: {
      business: ['Мастера выглядят по-разному', 'Нет единого стиля'],
      procurement: ['Сложно подобрать и брендировать форму', 'Нет простого решения'],
      exploitation: ['Логотип портится после стирок', 'Форма выглядит неаккуратно'],
    },
    solutions: [
      { title: 'Аккуратно наносим логотип на одежду', description: 'Качественный брендинг', type: 'process' },
      { title: 'Сохраняем эстетичный внешний вид', description: 'Чтобы форма выглядела частью бренда', type: 'product' },
      { title: 'Работаем с любой одеждой', description: 'Фартуки, футболки, поло', type: 'product' },
      { title: 'Поддерживаем единый стиль команды', description: 'Стабильность стиля', type: 'benefit' },
    ],
    bundles: [{ title: 'Комплект мастера', description: 'Футболка + фартук', items: ['Футболка', 'Фартук'] }],
    evidence: { cases: [{ type: 'real', title: 'Салон "Beauty"', description: 'Полный комплект формы', image: 'https://picsum.photos/seed/case4/400/300' }] },
    howItWorks: [
      { title: 'Оставляете заявку', description: 'Заполните форму, и мы свяжемся с вами' },
      { title: 'Уточняем задачу', description: 'Обсуждаем стиль и количество сотрудников' },
      { title: 'Предлагаем варианты', description: 'Подбираем одежду и метод нанесения' },
      { title: 'Согласовываем', description: 'Утверждаем макет и размеры' },
      { title: 'Производим и доставляем', description: 'Отшиваем партию и привозим вам' },
    ],
    form: {
      title: 'Подберем форму под ваш салон',
      subtitle: 'Предложим варианты под стиль и команду',
      submitLabel: 'Подобрать форму',
      fields: [
        { name: 'name', label: 'Имя', type: 'text', required: true },
        { name: 'phone', label: 'Телефон', type: 'tel', required: true },
        { name: 'staffCount', label: 'Количество сотрудников', type: 'number', required: true },
      ],
      hiddenFields: { segment: 'beauty', offer: 'uniform_beauty' },
      successMessage: 'Спасибо! Мы свяжемся с вами в ближайшее время.',
      formType: 'short',
      successAction: 'message',
    },
    faq: [{ q: 'Можно ли заказать разные размеры?', a: 'Да, конечно.' }],
    finalCta: {
      title: 'Сделаем ваш салон узнаваемым через форму',
      description: 'Получите расчет стоимости',
      buttonText: 'Получить расчет',
    },
    tracking: {
      segment: 'beauty',
      segmentLabel: 'Салоны красоты',
      offer: 'uniform_beauty',
      pageType: 'segment',
      scenarioId: 'beauty_scenario',
      pipeline: 'standard',
      tags: ['beauty'],
      formId: 'beauty_form',
      ownerQueue: 'sales',
      sourceDefault: 'website',
    },
    assets: {
      heroImage: 'https://picsum.photos/seed/beauty/1920/1080',
      ogImage: 'https://picsum.photos/seed/beauty/1200/630',
      hubCard: {
        icon: '💇‍♀️',
        title: 'Салоны красоты',
        description: 'Форма, которая усиливает имидж и аккуратный внешний вид мастеров.',
        cta: 'Посмотреть решение',
      },
    },
  },
  retail: {
    id: 'retail',
    slug: 'retail',
    name: 'Магазины',
    fullName: 'Форма для магазинов',
    status: 'active',
    priority: 'high',
    order: 5,
    featuredOnHome: true,
    seo: {
      title: 'Форма для продавцов магазинов',
      description: 'Единый фирменный стиль для персонала торговой точки.',
      h1: 'Форма для продавцов магазинов',
      ogImage: 'https://picsum.photos/seed/retail/1200/630',
    },
    hero: {
      title: 'Нанесем логотип на форму продавцов — чтобы бренд был узнаваем',
      subtitle: 'Быстро работаем с вашей одеждой',
      ctaPrimary: 'Подобрать форму',
      ctaSecondary: 'Смотреть примеры',
      benefits: ['Узнаваемость', 'Быстро', 'Ваша одежда'],
      microProof: 'Быстро работаем с вашей одеждой',
      image: 'https://picsum.photos/seed/retail/1920/1080',
    },
    forWhom: ['Магазины', 'Торговые сети', 'Бутики'],
    painPoints: {
      business: ['Продавцы выглядят по-разному', 'Нет узнаваемости бренда'],
      procurement: ['Нужно быстро брендировать форму', 'Нет удобного подрядчика'],
      exploitation: ['Логотип стирается', 'Одежда теряет внешний вид'],
    },
    solutions: [
      { title: 'Создаем единый стиль', description: 'Узнаваемый образ', type: 'product' },
      { title: 'Подбираем модели под формат магазина', description: 'Удобство и стиль', type: 'product' },
      { title: 'Наносим логотип', description: 'Брендинг', type: 'process' },
      { title: 'Упрощаем дозаказ', description: 'Система закупок', type: 'process' },
    ],
    bundles: [{ title: 'Комплект продавца', description: 'Футболка + фартук', items: ['Футболка', 'Фартук'] }],
    evidence: { cases: [{ type: 'real', title: 'Магазин "Стиль"', description: 'Полный комплект формы', image: 'https://picsum.photos/seed/case5/400/300' }] },
    howItWorks: [
      { title: 'Оставляете заявку', description: 'Заполните форму, и мы свяжемся с вами' },
      { title: 'Уточняем задачу', description: 'Обсуждаем формат и количество сотрудников' },
      { title: 'Предлагаем варианты', description: 'Подбираем одежду и метод нанесения' },
      { title: 'Согласовываем', description: 'Утверждаем макет и размеры' },
      { title: 'Производим и доставляем', description: 'Отшиваем партию и привозим вам' },
    ],
    form: {
      title: 'Подберем форму под ваш магазин',
      subtitle: 'Предложим варианты под формат и команду',
      submitLabel: 'Подобрать форму',
      fields: [
        { name: 'name', label: 'Имя', type: 'text', required: true },
        { name: 'phone', label: 'Телефон', type: 'tel', required: true },
        { name: 'staffCount', label: 'Количество сотрудников', type: 'number', required: true },
      ],
      hiddenFields: { segment: 'retail', offer: 'uniform_retail' },
      successMessage: 'Спасибо! Мы свяжемся с вами в ближайшее время.',
      formType: 'short',
      successAction: 'message',
    },
    faq: [{ q: 'Можно ли заказать разные размеры?', a: 'Да, конечно.' }],
    finalCta: { title: 'Готовы начать?', description: 'Подберем комплект под ваш штат', buttonText: 'Рассчитать' },
    tracking: {
      segment: 'retail',
      segmentLabel: 'Магазины',
      offer: 'uniform_retail',
      pageType: 'segment',
      scenarioId: 'retail_scenario',
      pipeline: 'standard',
      tags: ['retail'],
      formId: 'retail_form',
      ownerQueue: 'sales',
      sourceDefault: 'website',
    },
    assets: {
      heroImage: 'https://picsum.photos/seed/retail/1920/1080',
      ogImage: 'https://picsum.photos/seed/retail/1200/630',
      hubCard: {
        icon: '🛍️',
        title: 'Магазины',
        description: 'Форма для продавцов, которая делает бренд узнаваемым.',
        cta: 'Посмотреть решение',
      },
    },
  },
  fitness: {
    id: 'fitness',
    slug: 'fitness',
    name: 'Фитнес-клубы',
    fullName: 'Форма для фитнес-клубов',
    status: 'active',
    priority: 'medium',
    order: 6,
    featuredOnHome: false,
    seo: {
      title: 'Брендированная форма для фитнес-клубов',
      description: 'Одежда для тренеров и мерч для клуба.',
      h1: 'Брендированная форма для фитнес-клубов',
      ogImage: 'https://picsum.photos/seed/fitness/1200/630',
    },
    hero: {
      title: 'Нанесем логотип на форму тренеров и мерч клуба — чтобы бренд был заметен',
      subtitle: 'Работаем с любой одеждой и тиражами',
      ctaPrimary: 'Подобрать форму',
      ctaSecondary: 'Смотреть примеры',
      benefits: ['Заметность', 'Любая одежда', 'Тиражи'],
      microProof: 'Работаем с любой одеждой и тиражами',
      image: 'https://picsum.photos/seed/fitness/1920/1080',
    },
    forWhom: ['Фитнес-клубы', 'Спортивные секции', 'Йога-студии'],
    painPoints: {
      business: ['Тренеры выглядят по-разному', 'Нет единого стиля клуба'],
      procurement: ['Сложно сделать форму или мерч', 'Нет быстрого решения'],
      exploitation: ['Одежда быстро изнашивается', 'Логотип теряет внешний вид'],
    },
    solutions: [
      { title: 'Форма для тренеров', description: 'Удобная одежда', type: 'product' },
      { title: 'Мерч для клуба', description: 'Стильный мерч', type: 'product' },
      { title: 'Единый стиль', description: 'Поддержка бренда', type: 'benefit' },
    ],
    bundles: [{ title: 'Комплект тренера', description: 'Футболка + шорты', items: ['Футболка', 'Шорты'] }],
    evidence: { cases: [{ type: 'real', title: 'Клуб "Спорт"', description: 'Полный комплект формы', image: 'https://picsum.photos/seed/case6/400/300' }] },
    howItWorks: [
      { title: 'Оставляете заявку', description: 'Заполните форму, и мы свяжемся с вами' },
      { title: 'Уточняем задачу', description: 'Обсуждаем стиль и количество тренеров' },
      { title: 'Предлагаем варианты', description: 'Подбираем одежду и метод нанесения' },
      { title: 'Согласовываем', description: 'Утверждаем макет и размеры' },
      { title: 'Производим и доставляем', description: 'Отшиваем партию и привозим вам' },
    ],
    form: {
      title: 'Подберем форму и мерч под ваш клуб',
      subtitle: 'Предложим варианты под стиль и аудиторию',
      submitLabel: 'Подобрать форму',
      fields: [
        { name: 'name', label: 'Имя', type: 'text', required: true },
        { name: 'phone', label: 'Телефон', type: 'tel', required: true },
        { name: 'trainerCount', label: 'Количество тренеров', type: 'number', required: true },
      ],
      hiddenFields: { segment: 'fitness', offer: 'uniform_fitness' },
      successMessage: 'Спасибо! Мы свяжемся с вами в ближайшее время.',
      formType: 'short',
      successAction: 'message',
    },
    faq: [{ q: 'Можно ли заказать разные размеры?', a: 'Да, конечно.' }],
    finalCta: { title: 'Готовы начать?', description: 'Подберем комплект под ваш штат', buttonText: 'Рассчитать' },
    tracking: {
      segment: 'fitness',
      segmentLabel: 'Фитнес-клубы',
      offer: 'uniform_fitness',
      pageType: 'segment',
      scenarioId: 'fitness_scenario',
      pipeline: 'standard',
      tags: ['fitness'],
      formId: 'fitness_form',
      ownerQueue: 'sales',
      sourceDefault: 'website',
    },
    assets: {
      heroImage: 'https://picsum.photos/seed/fitness/1920/1080',
      ogImage: 'https://picsum.photos/seed/fitness/1200/630',
      hubCard: {
        icon: '💪',
        title: 'Фитнес-клубы',
        description: 'Форма и мерч, который усиливает бренд фитнес-клуба.',
        cta: 'Посмотреть решение',
      },
    },
  },
  cleaning: {
    id: 'cleaning',
    slug: 'cleaning',
    name: 'Клининговые компании',
    fullName: 'Форма для клининга',
    status: 'active',
    priority: 'medium',
    order: 7,
    featuredOnHome: false,
    seo: {
      title: 'Практичная униформа для клининга',
      description: 'Удобная одежда для клининга с логотипом.',
      h1: 'Практичная униформа для клининга',
      ogImage: 'https://picsum.photos/seed/cleaning/1200/630',
    },
    hero: {
      title: 'Нанесем логотип на форму для клининга — под частые стирки и работу',
      subtitle: 'Чтобы сотрудники выглядели аккуратно',
      ctaPrimary: 'Получить расчет',
      ctaSecondary: 'Смотреть примеры',
      benefits: ['Аккуратно', 'Стирки', 'Работа'],
      microProof: 'Чтобы сотрудники выглядели аккуратно',
      image: 'https://picsum.photos/seed/cleaning/1920/1080',
    },
    forWhom: ['Клининговые компании'],
    painPoints: {
      business: ['Сотрудники выглядят неаккуратно', 'Нет единого внешнего вида'],
      procurement: ['Сложно быстро сделать форму', 'Нет удобного решения'],
      exploitation: ['Частые стирки → логотип быстро портится', 'Форма теряет внешний вид'],
    },
    solutions: [
      { title: 'Практичные материалы', description: 'Удобство и долговечность', type: 'product' },
      { title: 'Удобные модели', description: 'Комфорт в работе', type: 'product' },
      { title: 'Наносим логотип', description: 'Узнаваемость', type: 'process' },
      { title: 'Дозаказы', description: 'Система закупок', type: 'process' },
    ],
    bundles: [{ title: 'Комплект клинера', description: 'Футболка + фартук', items: ['Футболка', 'Фартук'] }],
    evidence: { cases: [{ type: 'real', title: 'Клининг "Чисто"', description: 'Полный комплект формы', image: 'https://picsum.photos/seed/case7/400/300' }] },
    howItWorks: [
      { title: 'Оставляете заявку', description: 'Заполните форму, и мы свяжемся с вами' },
      { title: 'Уточняем задачу', description: 'Обсуждаем количество сотрудников' },
      { title: 'Предлагаем варианты', description: 'Подбираем одежду и метод нанесения' },
      { title: 'Согласовываем', description: 'Утверждаем макет и размеры' },
      { title: 'Производим и доставляем', description: 'Отшиваем партию и привозим вам' },
    ],
    form: {
      title: 'Подберем форму под вашу компанию',
      subtitle: 'Предложим варианты под задачи',
      submitLabel: 'Получить расчет',
      fields: [
        { name: 'name', label: 'Имя', type: 'text', required: true },
        { name: 'phone', label: 'Телефон', type: 'tel', required: true },
        { name: 'staffCount', label: 'Количество сотрудников', type: 'number', required: true },
      ],
      hiddenFields: { segment: 'cleaning', offer: 'uniform_cleaning' },
      successMessage: 'Спасибо! Мы свяжемся с вами в ближайшее время.',
      formType: 'short',
      successAction: 'message',
    },
    faq: [{ q: 'Можно ли заказать разные размеры?', a: 'Да, конечно.' }],
    finalCta: { title: 'Готовы начать?', description: 'Подберем комплект под ваш штат', buttonText: 'Рассчитать' },
    tracking: {
      segment: 'cleaning',
      segmentLabel: 'Клининговые компании',
      offer: 'uniform_cleaning',
      pageType: 'segment',
      scenarioId: 'cleaning_scenario',
      pipeline: 'standard',
      tags: ['cleaning'],
      formId: 'cleaning_form',
      ownerQueue: 'sales',
      sourceDefault: 'website',
    },
    assets: {
      heroImage: 'https://picsum.photos/seed/cleaning/1920/1080',
      ogImage: 'https://picsum.photos/seed/cleaning/1200/630',
      hubCard: {
        icon: '🧹',
        title: 'Клининговые компании',
        description: 'Практичная униформа для клининга с логотипом.',
        cta: 'Посмотреть решение',
      },
    },
  },
  delivery: {
    id: 'delivery',
    slug: 'delivery',
    name: 'Доставка',
    fullName: 'Форма для курьеров',
    status: 'active',
    priority: 'medium',
    order: 8,
    featuredOnHome: false,
    seo: {
      title: 'Удобная форма для курьеров',
      description: 'Узнаваемая одежда для курьеров с брендингом.',
      h1: 'Удобная форма для курьеров',
      ogImage: 'https://picsum.photos/seed/delivery/1200/630',
    },
    hero: {
      title: 'Нанесем логотип на форму курьеров — чтобы бренд был заметен в городе',
      subtitle: 'Быстро работаем с тиражами под команды',
      ctaPrimary: 'Получить расчет',
      ctaSecondary: 'Смотреть примеры',
      benefits: ['Заметность', 'Тиражи', 'Быстро'],
      microProof: 'Быстро работаем с тиражами под команды',
      image: 'https://picsum.photos/seed/delivery/1920/1080',
    },
    forWhom: ['Доставка', 'Логистика', 'Курьеры'],
    painPoints: {
      business: ['Курьеры выглядят по-разному', 'Нет узнаваемости бренда'],
      procurement: ['Нужно быстро брендировать форму', 'Часто требуется масштабирование'],
      exploitation: ['Одежда быстро изнашивается', 'Логотип теряет вид'],
    },
    solutions: [
      { title: 'Форма для курьеров', description: 'Удобная одежда', type: 'product' },
      { title: 'Брендирование', description: 'Нанесем логотип', type: 'process' },
    ],
    bundles: [{ title: 'Комплект курьера', description: 'Футболка + куртка', items: ['Футболка', 'Куртка'] }],
    evidence: { cases: [{ type: 'real', title: 'Доставка "Быстро"', description: 'Полный комплект формы', image: 'https://picsum.photos/seed/case8/400/300' }] },
    howItWorks: [
      { title: 'Оставляете заявку', description: 'Заполните форму, и мы свяжемся с вами' },
      { title: 'Уточняем задачу', description: 'Обсуждаем количество курьеров' },
      { title: 'Предлагаем варианты', description: 'Подбираем одежду и метод нанесения' },
      { title: 'Согласовываем', description: 'Утверждаем макет и размеры' },
      { title: 'Производим и доставляем', description: 'Отшиваем партию и привозим вам' },
    ],
    form: {
      title: 'Подберем форму под вашу доставку',
      subtitle: 'Свяжемся с вами и предложим варианты под ваш штат',
      submitLabel: 'Получить расчет',
      fields: [
        { name: 'name', label: 'Имя', type: 'text', required: true },
        { name: 'phone', label: 'Телефон', type: 'tel', required: true },
        { name: 'courierCount', label: 'Количество курьеров', type: 'number', required: true },
      ],
      hiddenFields: { segment: 'delivery', offer: 'uniform_delivery' },
      successMessage: 'Спасибо! Мы свяжемся с вами в ближайшее время.',
      formType: 'short',
      successAction: 'message',
    },
    faq: [{ q: 'Можно ли заказать разные размеры?', a: 'Да, конечно.' }],
    finalCta: { title: 'Готовы начать?', description: 'Подберем комплект под ваш штат', buttonText: 'Рассчитать' },
    tracking: {
      segment: 'delivery',
      segmentLabel: 'Доставка',
      offer: 'uniform_delivery',
      pageType: 'segment',
      scenarioId: 'delivery_scenario',
      pipeline: 'standard',
      tags: ['delivery'],
      formId: 'delivery_form',
      ownerQueue: 'sales',
      sourceDefault: 'website',
    },
    assets: {
      heroImage: 'https://picsum.photos/seed/delivery/1920/1080',
      ogImage: 'https://picsum.photos/seed/delivery/1200/630',
      hubCard: {
        icon: '🚚',
        title: 'Доставка',
        description: 'Узнаваемая одежда для курьеров с брендингом.',
        cta: 'Посмотреть решение',
      },
    },
  },
  construction: {
    id: 'construction',
    slug: 'construction',
    name: 'Строительство',
    fullName: 'Форма для строителей',
    status: 'active',
    priority: 'medium',
    order: 9,
    featuredOnHome: false,
    seo: {
      title: 'Прочная спецодежда для строителей',
      description: 'Износостойкая форма для строительных бригад.',
      h1: 'Прочная спецодежда для строителей',
      ogImage: 'https://picsum.photos/seed/construction/1200/630',
    },
    hero: {
      title: 'Нанесем логотип на рабочую форму — под реальные условия стройки',
      subtitle: 'Подбираем печать, которая держится при нагрузке',
      ctaPrimary: 'Получить расчет',
      ctaSecondary: 'Смотреть примеры',
      benefits: ['Прочность', 'Нагрузка', 'Стойкость'],
      microProof: 'Подбираем печать, которая держится при нагрузке',
      image: 'https://picsum.photos/seed/construction/1920/1080',
    },
    forWhom: ['Строительные компании', 'Бригады', 'Ремонт'],
    painPoints: {
      business: ['Бригады выглядят разрозненно', 'Нет единого фирменного вида'],
      procurement: ['Нужно быстро нанести логотип на форму', 'Важно работать с объемами'],
      exploitation: ['Форма быстро изнашивается', 'Логотип стирается и теряет вид'],
    },
    solutions: [
      { title: 'Прочные материалы', description: 'Износостойкость', type: 'product' },
      { title: 'Брендирование', description: 'Нанесем логотип', type: 'process' },
    ],
    bundles: [{ title: 'Комплект строителя', description: 'Куртка + брюки', items: ['Куртка', 'Брюки'] }],
    evidence: { cases: [{ type: 'real', title: 'Строительство "Дом"', description: 'Полный комплект формы', image: 'https://picsum.photos/seed/case9/400/300' }] },
    howItWorks: [
      { title: 'Оставляете заявку', description: 'Заполните форму, и мы свяжемся с вами' },
      { title: 'Уточняем задачу', description: 'Обсуждаем количество сотрудников' },
      { title: 'Предлагаем варианты', description: 'Подбираем одежду и метод нанесения' },
      { title: 'Согласовываем', description: 'Утверждаем макет и размеры' },
      { title: 'Производим и доставляем', description: 'Отшиваем партию и привозим вам' },
    ],
    form: {
      title: 'Подберем форму под вашу стройку',
      subtitle: 'Свяжемся с вами и предложим варианты под ваш штат',
      submitLabel: 'Получить расчет',
      fields: [
        { name: 'name', label: 'Имя', type: 'text', required: true },
        { name: 'phone', label: 'Телефон', type: 'tel', required: true },
        { name: 'staffCount', label: 'Количество сотрудников', type: 'number', required: true },
      ],
      hiddenFields: { segment: 'construction', offer: 'uniform_construction' },
      successMessage: 'Спасибо! Мы свяжемся с вами в ближайшее время.',
      formType: 'short',
      successAction: 'message',
    },
    faq: [{ q: 'Можно ли заказать разные размеры?', a: 'Да, конечно.' }],
    finalCta: { title: 'Готовы начать?', description: 'Подберем комплект под ваш штат', buttonText: 'Рассчитать' },
    tracking: {
      segment: 'construction',
      segmentLabel: 'Строительство',
      offer: 'uniform_construction',
      pageType: 'segment',
      scenarioId: 'construction_scenario',
      pipeline: 'standard',
      tags: ['construction'],
      formId: 'construction_form',
      ownerQueue: 'sales',
      sourceDefault: 'website',
    },
    assets: {
      heroImage: 'https://picsum.photos/seed/construction/1920/1080',
      ogImage: 'https://picsum.photos/seed/construction/1200/630',
      hubCard: {
        icon: '🏗️',
        title: 'Строительство',
        description: 'Прочная спецодежда для строительных бригад.',
        cta: 'Посмотреть решение',
      },
    },
  },
  medicine: {
    id: 'medicine',
    slug: 'medicine',
    name: 'Медицина',
    fullName: 'Форма для медиков',
    status: 'active',
    priority: 'medium',
    order: 10,
    featuredOnHome: false,
    seo: {
      title: 'Удобная форма для медиков',
      description: 'Комфортная одежда для врачей и персонала.',
      h1: 'Удобная форма для медиков',
      ogImage: 'https://picsum.photos/seed/medicine/1200/630',
    },
    hero: {
      title: 'Нанесем логотип на медицинскую форму — аккуратно, без потери внешнего вида',
      subtitle: 'Работаем с халатами, костюмами и готовой одеждой',
      ctaPrimary: 'Получить расчет',
      ctaSecondary: 'Смотреть примеры',
      benefits: ['Аккуратно', 'Без потери вида', 'Медицинская форма'],
      microProof: 'Работаем с халатами, костюмами и готовой одеждой',
      image: 'https://picsum.photos/seed/medicine/1920/1080',
    },
    forWhom: ['Клиники', 'Больницы', 'Стоматологии'],
    painPoints: {
      business: ['Нет единого внешнего вида у персонала', 'Важно поддерживать доверие через внешний вид'],
      procurement: ['Сложно быстро брендировать форму', 'Нет удобного решения без лишних этапов'],
      exploitation: ['Частые стирки → логотип быстро портится', 'Форма теряет аккуратность'],
    },
    solutions: [
      { title: 'Комфортные материалы', description: 'Гигиеничность', type: 'product' },
      { title: 'Брендирование', description: 'Нанесем логотип', type: 'process' },
    ],
    bundles: [{ title: 'Комплект врача', description: 'Халат + костюм', items: ['Халат', 'Костюм'] }],
    evidence: { cases: [{ type: 'real', title: 'Клиника "Здоровье"', description: 'Полный комплект формы', image: 'https://picsum.photos/seed/case10/400/300' }] },
    howItWorks: [
      { title: 'Оставляете заявку', description: 'Заполните форму, и мы свяжемся с вами' },
      { title: 'Уточняем задачу', description: 'Обсуждаем количество сотрудников' },
      { title: 'Предлагаем варианты', description: 'Подбираем одежду и метод нанесения' },
      { title: 'Согласовываем', description: 'Утверждаем макет и размеры' },
      { title: 'Производим и доставляем', description: 'Отшиваем партию и привозим вам' },
    ],
    form: {
      title: 'Подберем форму под вашу клинику',
      subtitle: 'Свяжемся с вами и предложим варианты под ваш штат',
      submitLabel: 'Получить расчет',
      fields: [
        { name: 'name', label: 'Имя', type: 'text', required: true },
        { name: 'phone', label: 'Телефон', type: 'tel', required: true },
        { name: 'staffCount', label: 'Количество сотрудников', type: 'number', required: true },
      ],
      hiddenFields: { segment: 'medicine', offer: 'uniform_medicine' },
      successMessage: 'Спасибо! Мы свяжемся с вами в ближайшее время.',
      formType: 'short',
      successAction: 'message',
    },
    faq: [{ q: 'Можно ли заказать разные размеры?', a: 'Да, конечно.' }],
    finalCta: { title: 'Готовы начать?', description: 'Подберем комплект под ваш штат', buttonText: 'Рассчитать' },
    tracking: {
      segment: 'medicine',
      segmentLabel: 'Медицина',
      offer: 'uniform_medicine',
      pageType: 'segment',
      scenarioId: 'medicine_scenario',
      pipeline: 'standard',
      tags: ['medicine'],
      formId: 'medicine_form',
      ownerQueue: 'sales',
      sourceDefault: 'website',
    },
    assets: {
      heroImage: 'https://picsum.photos/seed/medicine/1920/1080',
      ogImage: 'https://picsum.photos/seed/medicine/1200/630',
      hubCard: {
        icon: '🏥',
        title: 'Медицина',
        description: 'Комфортная одежда для врачей и персонала.',
        cta: 'Посмотреть решение',
      },
    },
  },
  veterinary: {
    id: 'veterinary',
    slug: 'veterinary',
    name: 'Ветеринария',
    fullName: 'Форма для ветеринаров',
    status: 'active',
    priority: 'medium',
    order: 11,
    featuredOnHome: false,
    seo: {
      title: 'Удобная форма для ветеринаров',
      description: 'Комфортная одежда для ветеринарных клиник.',
      h1: 'Удобная форма для ветеринаров',
      ogImage: 'https://picsum.photos/seed/veterinary/1200/630',
    },
    hero: {
      title: 'Нанесем логотип на форму для ветеринарной клиники — аккуратно и с учетом частых стирок',
      subtitle: 'Работаем с вашей одеждой, подбираем нанесение под ежедневную нагрузку',
      ctaPrimary: 'Получить расчет',
      ctaSecondary: 'Смотреть примеры',
      benefits: ['Аккуратно', 'Стойкость', 'Профессионализм'],
      microProof: 'Работаем с вашей одеждой, подбираем нанесение под ежедневную нагрузку',
      image: 'https://picsum.photos/seed/veterinary/1920/1080',
    },
    forWhom: ['Ветеринарные клиники', 'Приюты'],
    painPoints: {
      business: ['Персонал выглядит по-разному', 'Нет единого профессионального образа'],
      procurement: ['Сложно быстро брендировать форму', 'Нет удобного решения без лишних этапов'],
      exploitation: ['Форма часто стирается → логотип быстро портится', 'Одежда теряет аккуратный вид'],
    },
    solutions: [
      { title: 'Комфортные материалы', description: 'Гигиеничность', type: 'product' },
      { title: 'Брендирование', description: 'Нанесем логотип', type: 'process' },
    ],
    bundles: [{ title: 'Комплект ветеринара', description: 'Халат + костюм', items: ['Халат', 'Костюм'] }],
    evidence: { cases: [{ type: 'real', title: 'Клиника "Зверье"', description: 'Полный комплект формы', image: 'https://picsum.photos/seed/case11/400/300' }] },
    howItWorks: [
      { title: 'Оставляете заявку', description: 'Заполните форму, и мы свяжемся с вами' },
      { title: 'Уточняем задачу', description: 'Обсуждаем количество сотрудников' },
      { title: 'Предлагаем варианты', description: 'Подбираем одежду и метод нанесения' },
      { title: 'Согласовываем', description: 'Утверждаем макет и размеры' },
      { title: 'Производим и доставляем', description: 'Отшиваем партию и привозим вам' },
    ],
    form: {
      title: 'Подберем форму под вашу клинику',
      subtitle: 'Свяжемся с вами и предложим варианты под ваш штат',
      submitLabel: 'Получить расчет',
      fields: [
        { name: 'name', label: 'Имя', type: 'text', required: true },
        { name: 'phone', label: 'Телефон', type: 'tel', required: true },
        { name: 'staffCount', label: 'Количество сотрудников', type: 'number', required: true },
      ],
      hiddenFields: { segment: 'veterinary', offer: 'uniform_veterinary' },
      successMessage: 'Спасибо! Мы свяжемся с вами в ближайшее время.',
      formType: 'short',
      successAction: 'message',
    },
    faq: [{ q: 'Можно ли заказать разные размеры?', a: 'Да, конечно.' }],
    finalCta: { title: 'Готовы начать?', description: 'Подберем комплект под ваш штат', buttonText: 'Рассчитать' },
    tracking: {
      segment: 'veterinary',
      segmentLabel: 'Ветеринария',
      offer: 'uniform_veterinary',
      pageType: 'segment',
      scenarioId: 'veterinary_scenario',
      pipeline: 'standard',
      tags: ['veterinary'],
      formId: 'veterinary_form',
      ownerQueue: 'sales',
      sourceDefault: 'website',
    },
    assets: {
      heroImage: 'https://picsum.photos/seed/veterinary/1920/1080',
      ogImage: 'https://picsum.photos/seed/veterinary/1200/630',
      hubCard: {
        icon: '🐾',
        title: 'Ветеринария',
        description: 'Комфортная одежда для ветеринарных клиник.',
        cta: 'Посмотреть решение',
      },
    },
  },
  security: {
    id: 'security',
    slug: 'security',
    name: 'Охрана',
    fullName: 'Форма для охраны',
    status: 'active',
    priority: 'medium',
    order: 12,
    featuredOnHome: false,
    seo: {
      title: 'Прочная форма для охраны',
      description: 'Износостойкая одежда для сотрудников охраны.',
      h1: 'Прочная форма для охраны',
      ogImage: 'https://picsum.photos/seed/security/1200/630',
    },
    hero: {
      title: 'Нанесем логотип на форму охраны — строго, аккуратно и без потери внешнего вида',
      subtitle: 'Работаем с готовой формой, быстро делаем тиражи',
      ctaPrimary: 'Получить расчет',
      ctaSecondary: 'Смотреть примеры',
      benefits: ['Строго', 'Аккуратно', 'Без потери вида'],
      microProof: 'Работаем с готовой формой, быстро делаем тиражи',
      image: 'https://picsum.photos/seed/security/1920/1080',
    },
    forWhom: ['Охранные предприятия', 'ЧОП'],
    painPoints: {
      business: ['Нет единого внешнего вида у сотрудников', 'Форма не выглядит строго и профессионально'],
      procurement: ['Нужно быстро нанести логотип на форму', 'Важно одинаковое качество на всех комплектах'],
      exploitation: ['Логотип стирается и теряет четкость', 'Форма выглядит неаккуратно со временем'],
    },
    solutions: [
      { title: 'Прочные материалы', description: 'Износостойкость', type: 'product' },
      { title: 'Брендирование', description: 'Нанесем логотип', type: 'process' },
    ],
    bundles: [{ title: 'Комплект охранника', description: 'Куртка + брюки', items: ['Куртка', 'Брюки'] }],
    evidence: { cases: [{ type: 'real', title: 'ЧОП "Щит"', description: 'Полный комплект формы', image: 'https://picsum.photos/seed/case12/400/300' }] },
    howItWorks: [
      { title: 'Оставляете заявку', description: 'Заполните форму, и мы свяжемся с вами' },
      { title: 'Уточняем задачу', description: 'Обсуждаем количество сотрудников' },
      { title: 'Предлагаем варианты', description: 'Подбираем одежду и метод нанесения' },
      { title: 'Согласовываем', description: 'Утверждаем макет и размеры' },
      { title: 'Производим и доставляем', description: 'Отшиваем партию и привозим вам' },
    ],
    form: {
      title: 'Подберем форму под вашу охрану',
      subtitle: 'Свяжемся с вами и предложим варианты под ваш штат',
      submitLabel: 'Получить расчет',
      fields: [
        { name: 'name', label: 'Имя', type: 'text', required: true },
        { name: 'phone', label: 'Телефон', type: 'tel', required: true },
        { name: 'staffCount', label: 'Количество сотрудников', type: 'number', required: true },
      ],
      hiddenFields: { segment: 'security', offer: 'uniform_security' },
      successMessage: 'Спасибо! Мы свяжемся с вами в ближайшее время.',
      formType: 'short',
      successAction: 'message',
    },
    faq: [{ q: 'Можно ли заказать разные размеры?', a: 'Да, конечно.' }],
    finalCta: { title: 'Готовы начать?', description: 'Подберем комплект под ваш штат', buttonText: 'Рассчитать' },
    tracking: {
      segment: 'security',
      segmentLabel: 'Охрана',
      offer: 'uniform_security',
      pageType: 'segment',
      scenarioId: 'security_scenario',
      pipeline: 'standard',
      tags: ['security'],
      formId: 'security_form',
      ownerQueue: 'sales',
      sourceDefault: 'website',
    },
    assets: {
      heroImage: 'https://picsum.photos/seed/security/1920/1080',
      ogImage: 'https://picsum.photos/seed/security/1200/630',
      hubCard: {
        icon: '🛡️',
        title: 'Охрана',
        description: 'Прочная форма для сотрудников охраны.',
        cta: 'Посмотреть решение',
      },
    },
  },
  education: {
    id: 'education',
    slug: 'education',
    name: 'Образование',
    fullName: 'Форма для учебных заведений',
    status: 'active',
    priority: 'medium',
    order: 13,
    featuredOnHome: false,
    seo: {
      title: 'Удобная форма для учебных заведений',
      description: 'Комфортная одежда для персонала учебных заведений.',
      h1: 'Удобная форма для учебных заведений',
      ogImage: 'https://picsum.photos/seed/education/1200/630',
    },
    hero: {
      title: 'Нанесем логотип на форму и мерч для образовательного проекта — аккуратно и в едином стиле',
      subtitle: 'Работаем с футболками, худи и другой одеждой',
      ctaPrimary: 'Получить расчет',
      ctaSecondary: 'Смотреть примеры',
      benefits: ['Аккуратно', 'Единый стиль', 'Мерч'],
      microProof: 'Работаем с футболками, худи и другой одеждой',
      image: 'https://picsum.photos/seed/education/1920/1080',
    },
    forWhom: ['Школы', 'ВУЗы', 'Курсы'],
    painPoints: {
      business: ['Команда выглядит разрозненно', 'Нет узнаваемости проекта'],
      procurement: ['Сложно сделать мерч или форму быстро', 'Нет понятного подрядчика'],
      exploitation: ['Логотип теряет внешний вид', 'Одежда выглядит дешево после стирок'],
    },
    solutions: [
      { title: 'Комфортные материалы', description: 'Удобство', type: 'product' },
      { title: 'Брендирование', description: 'Нанесем логотип', type: 'process' },
    ],
    bundles: [{ title: 'Комплект сотрудника', description: 'Футболка + худи', items: ['Футболка', 'Худи'] }],
    evidence: { cases: [{ type: 'real', title: 'Школа "Знание"', description: 'Полный комплект формы', image: 'https://picsum.photos/seed/case13/400/300' }] },
    howItWorks: [
      { title: 'Оставляете заявку', description: 'Заполните форму, и мы свяжемся с вами' },
      { title: 'Уточняем задачу', description: 'Обсуждаем количество сотрудников' },
      { title: 'Предлагаем варианты', description: 'Подбираем одежду и метод нанесения' },
      { title: 'Согласовываем', description: 'Утверждаем макет и размеры' },
      { title: 'Производим и доставляем', description: 'Отшиваем партию и привозим вам' },
    ],
    form: {
      title: 'Подберем форму под ваше заведение',
      subtitle: 'Свяжемся с вами и предложим варианты под ваш штат',
      submitLabel: 'Получить расчет',
      fields: [
        { name: 'name', label: 'Имя', type: 'text', required: true },
        { name: 'phone', label: 'Телефон', type: 'tel', required: true },
        { name: 'staffCount', label: 'Количество сотрудников', type: 'number', required: true },
      ],
      hiddenFields: { segment: 'education', offer: 'uniform_education' },
      successMessage: 'Спасибо! Мы свяжемся с вами в ближайшее время.',
      formType: 'short',
      successAction: 'message',
    },
    faq: [{ q: 'Можно ли заказать разные размеры?', a: 'Да, конечно.' }],
    finalCta: { title: 'Готовы начать?', description: 'Подберем комплект под ваш штат', buttonText: 'Рассчитать' },
    tracking: {
      segment: 'education',
      segmentLabel: 'Образование',
      offer: 'uniform_education',
      pageType: 'segment',
      scenarioId: 'education_scenario',
      pipeline: 'standard',
      tags: ['education'],
      formId: 'education_form',
      ownerQueue: 'sales',
      sourceDefault: 'website',
    },
    assets: {
      heroImage: 'https://picsum.photos/seed/education/1920/1080',
      ogImage: 'https://picsum.photos/seed/education/1200/630',
      hubCard: {
        icon: '🎓',
        title: 'Образование',
        description: 'Комфортная одежда для персонала учебных заведений.',
        cta: 'Посмотреть решение',
      },
    },
  },
  events: {
    id: 'events',
    slug: 'events',
    name: 'Ивенты',
    fullName: 'Форма для ивентов',
    status: 'active',
    priority: 'medium',
    order: 14,
    featuredOnHome: false,
    seo: {
      title: 'Яркая форма для ивентов',
      description: 'Стильная одежда для персонала мероприятий.',
      h1: 'Яркая форма для ивентов',
      ogImage: 'https://picsum.photos/seed/events/1200/630',
    },
    hero: {
      title: 'Нанесем логотип на одежду для мероприятий — быстро и под нужный тираж',
      subtitle: 'Идеально для команд, промо и событий',
      ctaPrimary: 'Получить расчет',
      ctaSecondary: 'Смотреть примеры',
      benefits: ['Быстро', 'Тираж', 'Идеально'],
      microProof: 'Идеально для команд, промо и событий',
      image: 'https://picsum.photos/seed/events/1920/1080',
    },
    forWhom: ['Ивент-агентства', 'Промо-акции'],
    painPoints: {
      business: ['Команда на мероприятии выглядит разрозненно', 'Нет визуального единства'],
      procurement: ['Нужно сделать быстро', 'Важно уложиться в сроки'],
      exploitation: ['Важно, чтобы выглядело ярко и аккуратно', 'Печать не должна портиться в процессе'],
    },
    solutions: [
      { title: 'Яркие цвета', description: 'Заметность', type: 'product' },
      { title: 'Брендирование', description: 'Нанесем логотип', type: 'process' },
    ],
    bundles: [{ title: 'Комплект промоутера', description: 'Футболка + кепка', items: ['Футболка', 'Кепка'] }],
    evidence: { cases: [{ type: 'real', title: 'Ивент "Праздник"', description: 'Полный комплект формы', image: 'https://picsum.photos/seed/case14/400/300' }] },
    howItWorks: [
      { title: 'Оставляете заявку', description: 'Заполните форму, и мы свяжемся с вами' },
      { title: 'Уточняем задачу', description: 'Обсуждаем количество сотрудников' },
      { title: 'Предлагаем варианты', description: 'Подбираем одежду и метод нанесения' },
      { title: 'Согласовываем', description: 'Утверждаем макет и размеры' },
      { title: 'Производим и доставляем', description: 'Отшиваем партию и привозим вам' },
    ],
    form: {
      title: 'Подберем форму под ваше мероприятие',
      subtitle: 'Свяжемся с вами и предложим варианты под ваш штат',
      submitLabel: 'Получить расчет',
      fields: [
        { name: 'name', label: 'Имя', type: 'text', required: true },
        { name: 'phone', label: 'Телефон', type: 'tel', required: true },
        { name: 'staffCount', label: 'Количество сотрудников', type: 'number', required: true },
      ],
      hiddenFields: { segment: 'events', offer: 'uniform_events' },
      successMessage: 'Спасибо! Мы свяжемся с вами в ближайшее время.',
      formType: 'short',
      successAction: 'message',
    },
    faq: [{ q: 'Можно ли заказать разные размеры?', a: 'Да, конечно.' }],
    finalCta: { title: 'Готовы начать?', description: 'Подберем комплект под ваш штат', buttonText: 'Рассчитать' },
    tracking: {
      segment: 'events',
      segmentLabel: 'Ивенты',
      offer: 'uniform_events',
      pageType: 'segment',
      scenarioId: 'events_scenario',
      pipeline: 'standard',
      tags: ['events'],
      formId: 'events_form',
      ownerQueue: 'sales',
      sourceDefault: 'website',
    },
    assets: {
      heroImage: 'https://picsum.photos/seed/events/1920/1080',
      ogImage: 'https://picsum.photos/seed/events/1200/630',
      hubCard: {
        icon: '🎉',
        title: 'Ивенты',
        description: 'Яркая форма для персонала мероприятий.',
        cta: 'Посмотреть решение',
      },
    },
  },
};
